# Generated by Django 6.0.6 on 2026-08-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_company_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('request', 'Nova solicitação de entrega'), ('invoice', 'Pedido de faturamento'), ('company', 'Cadastro de empresa concluído')], max_length=10, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('body', models.TextField(blank=True, verbose_name='detalhes')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lido em')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.company', verbose_name='empresa de origem')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['read_at', '-created_at'], name='core_notifi_read_at_9ad1d7_idx')],
            },
        ),
    ]
