# Generated by Django 6.0.6 on 2026-08-12 01:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_company_registration'),
        ('operations', '0002_delivery_accepted_at_delivery_delivery_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_start', models.DateField(verbose_name='período de')),
                ('reference_end', models.DateField(verbose_name='período até')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('status', models.CharField(choices=[('open', 'A pagar'), ('paid', 'Pago')], default='open', max_length=6, verbose_name='situação')),
                ('method', models.CharField(blank=True, max_length=40, verbose_name='forma de pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='operations.driver', verbose_name='entregador')),
            ],
            options={
                'verbose_name': 'repasse ao entregador',
                'verbose_name_plural': 'repasses aos entregadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('24.90'), max_digits=10, verbose_name='valor base da entrega')),
                ('price_per_extra_stop', models.DecimalField(decimal_places=2, default=Decimal('9.90'), max_digits=10, verbose_name='valor por destino adicional')),
                ('urgent_surcharge', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=10, verbose_name='acréscimo urgente')),
                ('critical_surcharge', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=10, verbose_name='acréscimo crítico')),
                ('driver_share_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='percentual do entregador')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tabela de preços',
                'verbose_name_plural': 'tabela de preços',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número')),
                ('kind', models.CharField(choices=[('boleto', 'Boleto bancário'), ('recibo', 'Recibo (Pix ou dinheiro)')], default='boleto', max_length=8, verbose_name='forma de cobrança')),
                ('status', models.CharField(choices=[('open', 'Aguardando emissão'), ('issued', 'Boleto emitido'), ('paid', 'Paga'), ('canceled', 'Cancelada')], default='open', max_length=10, verbose_name='situação')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='boleto emitido em')),
                ('bank_slip_line', models.CharField(blank=True, help_text='Colada do internet banking. A emissão do boleto é feita no banco.', max_length=60, verbose_name='linha digitável')),
                ('bank_slip_url', models.URLField(blank=True, verbose_name='link do boleto no banco')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paga em')),
                ('payment_method', models.CharField(blank=True, max_length=40, verbose_name='forma de pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.company', verbose_name='empresa')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='finance_inv_company_b54bdb_idx'), models.Index(fields=['status', 'due_date'], name='finance_inv_status_0e2dc8_idx')],
            },
        ),
    ]
