# Generated by Django 6.0.6 on 2026-08-12 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('operations', '0004_driver_address_driver_bank_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driverpayout',
            index=models.Index(fields=['driver', 'status'], name='repasse_por_entregador'),
        ),
        migrations.AddIndex(
            model_name='driverpayout',
            index=models.Index(fields=['status', '-created_at'], name='repasse_status_recentes'),
        ),
    ]
