# Generated by Django 6.0.6 on 2026-08-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_platform',
            field=models.BooleanField(default=False, help_text='Marque somente para a Camboriú Delivery. A frota e os entregadores pertencem a ela.', verbose_name='transportadora da plataforma'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador'), ('dispatcher', 'Central de despacho'), ('driver', 'Entregador')], default='viewer', max_length=12, verbose_name='papel'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform', True)), fields=('is_platform',), name='single_platform_company'),
        ),
    ]
