# Generated by Django 6.0.6 on 2026-08-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_is_platform_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=90, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações internas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', 'Admin master'), ('dispatcher', 'Central de despacho'), ('owner', 'Proprietário'), ('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador'), ('driver', 'Entregador')], default='viewer', max_length=12, verbose_name='papel'),
        ),
    ]
