# Generated by Django 6.0.6 on 2026-08-12 21:53

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_proof',
            field=models.FileField(blank=True, help_text='Conta de água, luz ou telefone dos últimos três meses.', upload_to=core.uploads.company_document_path, validators=[core.uploads.validate_document_file], verbose_name='comprovante de endereço'),
        ),
        migrations.AddField(
            model_name='company',
            name='articles_of_association',
            field=models.FileField(blank=True, upload_to=core.uploads.company_document_path, validators=[core.uploads.validate_document_file], verbose_name='contrato social ou certificado MEI'),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail do financeiro'),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone do financeiro'),
        ),
        migrations.AddField(
            model_name='company',
            name='business_area',
            field=models.CharField(blank=True, max_length=120, verbose_name='ramo de atividade'),
        ),
        migrations.AddField(
            model_name='company',
            name='complement',
            field=models.CharField(blank=True, max_length=90, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_document',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do responsável'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_document_file',
            field=models.FileField(blank=True, upload_to=core.uploads.company_document_path, validators=[core.uploads.validate_document_file], verbose_name='documento com foto do responsável'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_role',
            field=models.CharField(blank=True, max_length=90, verbose_name='cargo do responsável'),
        ),
        migrations.AddField(
            model_name='company',
            name='document_file',
            field=models.FileField(blank=True, upload_to=core.uploads.company_document_path, validators=[core.uploads.validate_document_file], verbose_name='cartão CNPJ ou documento do titular'),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_on',
            field=models.DateField(blank=True, null=True, verbose_name='data de abertura'),
        ),
        migrations.AddField(
            model_name='company',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=30, verbose_name='inscrição municipal'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_regime',
            field=models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('mei', 'MEI'), ('presumido', 'Lucro presumido'), ('real', 'Lucro real'), ('pf', 'Pessoa física')], max_length=10, verbose_name='regime tributário'),
        ),
    ]
