"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

from core.deploy import (
    CHAVE_DESENVOLVIMENTO, debug_default, env_flag, env_float, env_int, env_value,
    extra_hosts, extra_origins, falhas_de_deploy, inspecao_de_build, merge_unique,
    object_storage_from_env, on_vercel, r2_client_config, serverless_database,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    """Lê um .env simples (CHAVE=valor). Variáveis já definidas no sistema têm prioridade."""
    if not path.exists():
        return
    for linha in path.read_text(encoding="utf-8").splitlines():
        linha = linha.strip()
        if not linha or linha.startswith("#") or "=" not in linha:
            continue
        chave, _, valor = linha.partition("=")
        os.environ.setdefault(chave.strip(), valor.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / ".env")


def flag(name, default=False):
    return env_flag(os.environ, name, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_value(os.environ, "SECRET_KEY", CHAVE_DESENVOLVIMENTO)

# SECURITY WARNING: don't run with debug turned on in production!
ON_VERCEL = on_vercel(os.environ)
DEBUG = flag("DEBUG", debug_default(os.environ))
COMANDO_SEM_BANCO = inspecao_de_build(os.environ, sys.argv)
FALHAS_DE_DEPLOY = []

# Perfis de demonstração no login (e-mails e senha na tela). Só existem fora de produção.
DEMO_MODE = flag("DEMO_MODE", DEBUG and not ON_VERCEL)

ALLOWED_HOSTS = [host.strip() for host in env_value(os.environ, "ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host.strip()]
ALLOWED_HOSTS = merge_unique(ALLOWED_HOSTS, extra_hosts(os.environ))
CSRF_TRUSTED_ORIGINS = [url.strip() for url in env_value(os.environ, "CSRF_TRUSTED_ORIGINS", "").split(",") if url.strip()]
CSRF_TRUSTED_ORIGINS = merge_unique(CSRF_TRUSTED_ORIGINS, extra_origins(os.environ))
if DEBUG:
    for origin in ("http://127.0.0.1:8000", "http://localhost:8000"):
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'accounts',
    'operations',
    'finance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.deploy_guard.DeployGuardMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.panel',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

SUPABASE_TRANSACTION_POOLER_PORT = "6543"


def postgres_config(name, user, password, host, port):
    """Conexão PostgreSQL/Supabase com TLS e reaproveitamento de conexão.

    O pooler do Supabase na porta 6543 trabalha em modo transação: nele não dá para
    manter conexão aberta nem usar cursor no servidor. Na 5432 (sessão ou direta) dá.
    """
    transaction_pooler = str(port) == SUPABASE_TRANSACTION_POOLER_PORT
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": str(port),
        "CONN_MAX_AGE": 0 if transaction_pooler else env_int(os.environ, "CONN_MAX_AGE", 600),
        "CONN_HEALTH_CHECKS": not transaction_pooler,
        "DISABLE_SERVER_SIDE_CURSORS": transaction_pooler,
        "ATOMIC_REQUESTS": False,
        "OPTIONS": {
            # Supabase só aceita conexão cifrada; sem isso a credencial trafega em claro.
            "sslmode": env_value(os.environ, "PGSSLMODE", "require"),
            "connect_timeout": env_int(os.environ, "PGCONNECT_TIMEOUT", 10),
            "application_name": env_value(os.environ, "PGAPPNAME", "camboriu-delivery"),
        },
    }


def database_from_url(url):
    parsed = urlparse(url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured("DATABASE_URL precisa começar com postgresql://")
    return postgres_config(
        name=(parsed.path or "/postgres").lstrip("/") or "postgres",
        user=unquote(parsed.username or ""),
        password=unquote(parsed.password or ""),
        host=parsed.hostname or "",
        port=parsed.port or 5432,
    )


# A suíte cria e destrói um banco próprio, coisa que o pooler do Supabase não faz (ele
# entrega sempre o banco do projeto). Por isso `manage.py test` roda em SQLite, a menos
# que TEST_ON_CONFIGURED_DB aponte para um PostgreSQL de teste de verdade.
RODANDO_TESTES = sys.argv[1:2] == ["test"] and not flag("TEST_ON_CONFIGURED_DB")

# DATABASE_URL é o caminho usado com o Supabase; POSTGRES_* segue valendo para outro servidor.
if RODANDO_TESTES:
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.test.sqlite3"}}
elif env_value(os.environ, "DATABASE_URL"):
    try:
        DATABASES = {"default": database_from_url(os.environ["DATABASE_URL"])}
    except ImproperlyConfigured:
        FALHAS_DE_DEPLOY.append("DATABASE_URL")
        DATABASES = {"default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "/tmp/camboriu-deploy.sqlite3" if ON_VERCEL else str(BASE_DIR / "db.sqlite3"),
        }}
elif env_value(os.environ, "POSTGRES_DB"):
    DATABASES = {"default": postgres_config(
        name=os.environ["POSTGRES_DB"],
        user=env_value(os.environ, "POSTGRES_USER", ""),
        password=env_value(os.environ, "POSTGRES_PASSWORD", ""),
        host=env_value(os.environ, "POSTGRES_HOST", "localhost"),
        port=env_value(os.environ, "POSTGRES_PORT", "5432"),
    )}
else:
    DATABASES = {"default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": env_value(os.environ, "SQLITE_PATH", str(BASE_DIR / "db.sqlite3")),
        "OPTIONS": {"transaction_mode": "IMMEDIATE", "init_command": "PRAGMA journal_mode=WAL;"},
    }}

if ON_VERCEL:
    DATABASES["default"] = serverless_database(DATABASES["default"], os.environ)

OBJECT_STORAGE, OBJECT_STORAGE_GAPS = object_storage_from_env(os.environ)
if RODANDO_TESTES:
    OBJECT_STORAGE = None

FALHAS_DE_DEPLOY = list(dict.fromkeys(FALHAS_DE_DEPLOY + falhas_de_deploy(
    debug=DEBUG,
    testes=RODANDO_TESTES,
    inspecao=COMANDO_SEM_BANCO,
    chave=SECRET_KEY,
    sqlite=DATABASES["default"]["ENGINE"].endswith("sqlite3"),
    storage_gaps=OBJECT_STORAGE_GAPS if ON_VERCEL else (),
)))
if "SECRET_KEY" in FALHAS_DE_DEPLOY:
    # Django precisa de alguma chave só para o processo subir e mostrar o 503.
    SECRET_KEY = env_value(os.environ, "VERCEL_GIT_COMMIT_SHA", CHAVE_DESENVOLVIMENTO) or CHAVE_DESENVOLVIMENTO


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': env_int(os.environ, "MIN_PASSWORD_LENGTH", 10)},
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Argon2 é o hash recomendado hoje; sem a biblioteca instalada seguimos no PBKDF2 do Django,
# e as senhas antigas continuam sendo aceitas nos dois casos.
try:  # pragma: no cover - depende do que está instalado no servidor
    import argon2  # noqa: F401

    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.Argon2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
        "django.contrib.auth.hashers.ScryptPasswordHasher",
    ]
except ImportError:
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
        "django.contrib.auth.hashers.ScryptPasswordHasher",
    ]

if RODANDO_TESTES:
    # Argon2 leva quase um segundo por senha de propósito. Na suíte, que cria centenas
    # de contas, isso vira minutos de espera sem testar nada além da biblioteca.
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"] + PASSWORD_HASHERS

# Tentativas de login. Passou do limite, a conta espera antes de tentar de novo.
LOGIN_ATTEMPT_LIMIT = env_int(os.environ, "LOGIN_ATTEMPT_LIMIT", 8)
LOGIN_ATTEMPT_WINDOW_SECONDS = env_int(os.environ, "LOGIN_ATTEMPT_WINDOW_SECONDS", 900)

CACHES = {"default": {
    "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    "LOCATION": "camboriu-delivery",
}}
if os.getenv("REDIS_URL"):
    # Com mais de um processo web o bloqueio de login precisa de cache compartilhado.
    CACHES["default"] = {"BACKEND": "django.core.cache.backends.redis.RedisCache", "LOCATION": os.environ["REDIS_URL"]}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_USE_FINDERS = DEBUG

# Fotos do checklist, CNH e contratos. Em disco só no desenvolvimento; na Vercel o destino é o R2.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(env_value(os.environ, "MEDIA_ROOT", "/tmp/camboriu-media" if ON_VERCEL else str(BASE_DIR / "media")))
FILE_UPLOAD_PERMISSIONS = 0o640
if ON_VERCEL:
    FILE_UPLOAD_TEMP_DIR = next(
        (pasta for pasta in ("/tmp", os.getenv("TEMP"), os.getenv("TMP")) if pasta and os.path.isdir(pasta)),
        str(BASE_DIR),
    )

CHECKLIST_MAX_PHOTO_MB = env_int(os.environ, "CHECKLIST_MAX_PHOTO_MB", 1 if ON_VERCEL else 12)
TRACKING_PING_SECONDS = env_int(os.environ, "TRACKING_PING_SECONDS", 15)
TRACKING_STALE_SECONDS = env_int(os.environ, "TRACKING_STALE_SECONDS", 180)

# Leaflet é open source e o OpenStreetMap não exige token. Troque por um provedor com chave se precisar de mais volume.
MAP_TILE_URL = env_value(os.environ, "MAP_TILE_URL", "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")
MAP_TILE_ATTRIBUTION = env_value(os.environ, "MAP_TILE_ATTRIBUTION", "© OpenStreetMap")
MAP_DEFAULT_LAT = env_float(os.environ, "MAP_DEFAULT_LAT", -26.9906)
MAP_DEFAULT_LNG = env_float(os.environ, "MAP_DEFAULT_LNG", -48.6349)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
CSRF_FAILURE_VIEW = 'core.auth_views.csrf_failure'
# O token vai no formulário e no atributo data-csrf; nenhum script lê o cookie.
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_AGE = env_int(os.environ, "SESSION_COOKIE_AGE", 12 * 60 * 60)
# Sessão lida do cache e gravada no banco: menos ida ao Postgres a cada clique.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = flag("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = env_int(os.environ, "SECURE_HSTS_SECONDS", 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
# Atrás de proxy/CDN (Nginx, Cloudflare, Fly, Render) é assim que o Django sabe que a origem era HTTPS.
if flag("USE_X_FORWARDED_PROTO", not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = flag("USE_X_FORWARDED_HOST", False)

# O checklist envia 12 fotos de uma vez; o resto do formulário continua pequeno.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 800
DATA_UPLOAD_MAX_NUMBER_FILES = 40

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Em produção o nome do arquivo leva o hash do conteúdo: cache longo no navegador
    # sem risco de servir CSS velho. Exige rodar collectstatic no deploy.
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if ON_VERCEL
            else (
                "whitenoise.storage.CompressedManifestStaticFilesStorage"
                if flag("STATIC_MANIFEST", not DEBUG)
                else "whitenoise.storage.CompressedStaticFilesStorage"
            )
        ),
    },
}

# R2 da Cloudflare (API S3). Bucket privado: o download continua pelas views autenticadas.
if OBJECT_STORAGE:
    os.environ.setdefault("AWS_REQUEST_CHECKSUM_CALCULATION", "WHEN_REQUIRED")
    os.environ.setdefault("AWS_RESPONSE_CHECKSUM_VALIDATION", "WHEN_REQUIRED")
    opcoes = dict(OBJECT_STORAGE)
    opcoes["client_config"] = r2_client_config()
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": opcoes,
    }

LOG_LEVEL = env_value(os.environ, "LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"padrao": {"format": "{asctime} {levelname} {name} {message}", "style": "{"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "padrao"}},
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    "loggers": {
        # Tentativa de host proibido, CSRF quebrado e afins viram aviso no log.
        "django.security": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "camboriu": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
    },
}
