"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

from core.deploy import (
    debug_default, extra_hosts, extra_origins, merge_unique, on_vercel, serverless_database,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    """Lê um .env simples (CHAVE=valor). Variáveis já definidas no sistema têm prioridade."""
    if not path.exists():
        return
    for linha in path.read_text(encoding="utf-8").splitlines():
        linha = linha.strip()
        if not linha or linha.startswith("#") or "=" not in linha:
            continue
        chave, _, valor = linha.partition("=")
        os.environ.setdefault(chave.strip(), valor.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / ".env")


def flag(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-development-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
ON_VERCEL = on_vercel(os.environ)
DEBUG = flag("DEBUG", debug_default(os.environ))
COMANDO = sys.argv[1] if len(sys.argv) > 1 else ""
if (
    not DEBUG
    and SECRET_KEY == "django-insecure-development-only-change-me"
    and COMANDO not in {"collectstatic"}
):
    raise ImproperlyConfigured("Defina SECRET_KEY quando DEBUG=False.")

# Perfis de demonstração no login (e-mails e senha na tela). Só existem fora de produção.
DEMO_MODE = flag("DEMO_MODE", DEBUG and not ON_VERCEL)

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host.strip()]
ALLOWED_HOSTS = merge_unique(ALLOWED_HOSTS, extra_hosts(os.environ))
CSRF_TRUSTED_ORIGINS = [url.strip() for url in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if url.strip()]
CSRF_TRUSTED_ORIGINS = merge_unique(CSRF_TRUSTED_ORIGINS, extra_origins(os.environ))
if DEBUG:
    for origin in ("http://127.0.0.1:8000", "http://localhost:8000"):
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'accounts',
    'operations',
    'finance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.panel',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

SUPABASE_TRANSACTION_POOLER_PORT = "6543"


def postgres_config(name, user, password, host, port):
    """Conexão PostgreSQL/Supabase com TLS e reaproveitamento de conexão.

    O pooler do Supabase na porta 6543 trabalha em modo transação: nele não dá para
    manter conexão aberta nem usar cursor no servidor. Na 5432 (sessão ou direta) dá.
    """
    transaction_pooler = str(port) == SUPABASE_TRANSACTION_POOLER_PORT
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": str(port),
        "CONN_MAX_AGE": 0 if transaction_pooler else int(os.getenv("CONN_MAX_AGE", "600")),
        "CONN_HEALTH_CHECKS": not transaction_pooler,
        "DISABLE_SERVER_SIDE_CURSORS": transaction_pooler,
        "ATOMIC_REQUESTS": False,
        "OPTIONS": {
            # Supabase só aceita conexão cifrada; sem isso a credencial trafega em claro.
            "sslmode": os.getenv("PGSSLMODE", "require"),
            "connect_timeout": int(os.getenv("PGCONNECT_TIMEOUT", "10")),
            "application_name": os.getenv("PGAPPNAME", "camboriu-delivery"),
        },
    }


def database_from_url(url):
    parsed = urlparse(url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured("DATABASE_URL precisa começar com postgresql://")
    return postgres_config(
        name=(parsed.path or "/postgres").lstrip("/") or "postgres",
        user=unquote(parsed.username or ""),
        password=unquote(parsed.password or ""),
        host=parsed.hostname or "",
        port=parsed.port or 5432,
    )


# A suíte cria e destrói um banco próprio, coisa que o pooler do Supabase não faz (ele
# entrega sempre o banco do projeto). Por isso `manage.py test` roda em SQLite, a menos
# que TEST_ON_CONFIGURED_DB aponte para um PostgreSQL de teste de verdade.
RODANDO_TESTES = sys.argv[1:2] == ["test"] and not flag("TEST_ON_CONFIGURED_DB")

# DATABASE_URL é o caminho usado com o Supabase; POSTGRES_* segue valendo para outro servidor.
if RODANDO_TESTES:
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.test.sqlite3"}}
elif os.getenv("DATABASE_URL"):
    DATABASES = {"default": database_from_url(os.environ["DATABASE_URL"])}
elif os.getenv("POSTGRES_DB"):
    DATABASES = {"default": postgres_config(
        name=os.environ["POSTGRES_DB"],
        user=os.getenv("POSTGRES_USER", ""),
        password=os.getenv("POSTGRES_PASSWORD", ""),
        host=os.getenv("POSTGRES_HOST", "localhost"),
        port=os.getenv("POSTGRES_PORT", "5432"),
    )}
else:
    DATABASES = {"default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("SQLITE_PATH", BASE_DIR / "db.sqlite3"),
        "OPTIONS": {"transaction_mode": "IMMEDIATE", "init_command": "PRAGMA journal_mode=WAL;"},
    }}

if ON_VERCEL:
    DATABASES["default"] = serverless_database(DATABASES["default"], os.environ)

if not DEBUG and not RODANDO_TESTES and DATABASES["default"]["ENGINE"].endswith("sqlite3"):
    raise ImproperlyConfigured("Em produção configure DATABASE_URL (Supabase) — SQLite não aguenta a operação.")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': int(os.getenv("MIN_PASSWORD_LENGTH", "10"))},
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Argon2 é o hash recomendado hoje; sem a biblioteca instalada seguimos no PBKDF2 do Django,
# e as senhas antigas continuam sendo aceitas nos dois casos.
try:  # pragma: no cover - depende do que está instalado no servidor
    import argon2  # noqa: F401

    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.Argon2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
        "django.contrib.auth.hashers.ScryptPasswordHasher",
    ]
except ImportError:
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
        "django.contrib.auth.hashers.ScryptPasswordHasher",
    ]

if RODANDO_TESTES:
    # Argon2 leva quase um segundo por senha de propósito. Na suíte, que cria centenas
    # de contas, isso vira minutos de espera sem testar nada além da biblioteca.
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"] + PASSWORD_HASHERS

# Tentativas de login. Passou do limite, a conta espera antes de tentar de novo.
LOGIN_ATTEMPT_LIMIT = int(os.getenv("LOGIN_ATTEMPT_LIMIT", "8"))
LOGIN_ATTEMPT_WINDOW_SECONDS = int(os.getenv("LOGIN_ATTEMPT_WINDOW_SECONDS", "900"))

CACHES = {"default": {
    "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    "LOCATION": "camboriu-delivery",
}}
if os.getenv("REDIS_URL"):
    # Com mais de um processo web o bloqueio de login precisa de cache compartilhado.
    CACHES["default"] = {"BACKEND": "django.core.cache.backends.redis.RedisCache", "LOCATION": os.environ["REDIS_URL"]}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_USE_FINDERS = DEBUG

# Fotos do checklist antifraude. Em produção aponte MEDIA_ROOT para um volume com backup e acesso restrito.
# Na Vercel o disco some a cada request: sem S3/Supabase Storage o arquivo não sobrevive.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", "/tmp/camboriu-media" if ON_VERCEL else BASE_DIR / "media"))
FILE_UPLOAD_PERMISSIONS = 0o640
if ON_VERCEL:
    FILE_UPLOAD_TEMP_DIR = "/tmp"

CHECKLIST_MAX_PHOTO_MB = int(os.getenv("CHECKLIST_MAX_PHOTO_MB", "12"))
TRACKING_PING_SECONDS = int(os.getenv("TRACKING_PING_SECONDS", "15"))
TRACKING_STALE_SECONDS = int(os.getenv("TRACKING_STALE_SECONDS", "180"))

# Leaflet é open source e o OpenStreetMap não exige token. Troque por um provedor com chave se precisar de mais volume.
MAP_TILE_URL = os.getenv("MAP_TILE_URL", "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")
MAP_TILE_ATTRIBUTION = os.getenv("MAP_TILE_ATTRIBUTION", "© OpenStreetMap")
MAP_DEFAULT_LAT = float(os.getenv("MAP_DEFAULT_LAT", "-26.9906"))
MAP_DEFAULT_LNG = float(os.getenv("MAP_DEFAULT_LNG", "-48.6349"))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
CSRF_FAILURE_VIEW = 'core.auth_views.csrf_failure'
# O token vai no formulário e no atributo data-csrf; nenhum script lê o cookie.
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", str(12 * 60 * 60)))
# Sessão lida do cache e gravada no banco: menos ida ao Postgres a cada clique.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = flag("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
# Atrás de proxy/CDN (Nginx, Cloudflare, Fly, Render) é assim que o Django sabe que a origem era HTTPS.
if flag("USE_X_FORWARDED_PROTO", not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = flag("USE_X_FORWARDED_HOST", False)

# O checklist envia 12 fotos de uma vez; o resto do formulário continua pequeno.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 800
DATA_UPLOAD_MAX_NUMBER_FILES = 40

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Em produção o nome do arquivo leva o hash do conteúdo: cache longo no navegador
    # sem risco de servir CSS velho. Exige rodar collectstatic no deploy.
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if flag("STATIC_MANIFEST", not DEBUG)
            else "whitenoise.storage.CompressedStaticFilesStorage"
        ),
    },
}

# Supabase Storage (S3). Sem essas chaves a Vercel não consegue guardar foto de checklist.
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID") or os.getenv("SUPABASE_S3_ACCESS_KEY", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY") or os.getenv("SUPABASE_S3_SECRET_KEY", "")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "media")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "sa-east-1")
AWS_S3_ENDPOINT_URL = os.getenv(
    "AWS_S3_ENDPOINT_URL",
    f"https://{os.getenv('SUPABASE_PROJECT_REF', 'qnfhfgqnvhhhkiobxpff')}.storage.supabase.co/storage/v1/s3",
)
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_MAX_MEMORY_SIZE = 5 * 1024 * 1024
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    STORAGES["default"] = {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"}

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"padrao": {"format": "{asctime} {levelname} {name} {message}", "style": "{"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "padrao"}},
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    "loggers": {
        # Tentativa de host proibido, CSRF quebrado e afins viram aviso no log.
        "django.security": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "camboriu": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
    },
}
