# Generated by Django 6.0.6 on 2026-08-11 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=24, unique=True, verbose_name='código')),
                ('requester', models.CharField(max_length=160, verbose_name='cliente solicitante')),
                ('item_type', models.CharField(choices=[('document', 'Documento'), ('high_value', 'Alto valor'), ('medicine', 'Medicamento'), ('sample', 'Amostra'), ('other', 'Outro')], max_length=15, verbose_name='tipo de item')),
                ('description', models.TextField(verbose_name='descrição')),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor declarado')),
                ('confidential', models.BooleanField(default=False, verbose_name='sigiloso')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='endereço de coleta')),
                ('pickup_contact', models.CharField(max_length=160, verbose_name='contato da coleta')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='endereço de entrega')),
                ('delivery_contact', models.CharField(max_length=160, verbose_name='contato da entrega')),
                ('pickup_window', models.DateTimeField(blank=True, null=True, verbose_name='janela de coleta')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgente'), ('critical', 'Crítica')], default='normal', max_length=10, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('approved', 'Aprovada'), ('pickup', 'Em coleta'), ('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('canceled', 'Cancelada')], default='requested', max_length=12)),
                ('proof', models.CharField(blank=True, max_length=255, verbose_name='comprovante')),
                ('receiver', models.CharField(blank=True, max_length=160, verbose_name='recebedor')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('approved', 'Aprovada'), ('pickup', 'Em coleta'), ('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('canceled', 'Cancelada')], max_length=12)),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.delivery')),
            ],
            options={
                'verbose_name': 'evento da entrega',
                'verbose_name_plural': 'eventos das entregas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('cnh', models.CharField(max_length=20, verbose_name='CNH')),
                ('cnh_category', models.CharField(max_length=5, verbose_name='categoria CNH')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('away', 'Afastado')], default='active', max_length=12)),
                ('contract_type', models.CharField(choices=[('employee', 'CLT'), ('contractor', 'Prestador'), ('partner', 'Parceiro')], max_length=15, verbose_name='vínculo')),
                ('cnh_expires_at', models.DateField(blank=True, null=True, verbose_name='vencimento da CNH')),
                ('medical_exam_expires_at', models.DateField(blank=True, null=True, verbose_name='vencimento do exame')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'motorista',
                'verbose_name_plural': 'motoristas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.driver', verbose_name='motorista'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('motorcycle', 'Moto'), ('car', 'Carro'), ('utility', 'Utilitário')], max_length=12, verbose_name='tipo')),
                ('plate', models.CharField(max_length=10, verbose_name='placa')),
                ('brand', models.CharField(max_length=60, verbose_name='marca')),
                ('model', models.CharField(max_length=80, verbose_name='modelo')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='capacidade (kg)')),
                ('equipment', models.CharField(blank=True, max_length=255, verbose_name='baú/equipamentos')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('in_use', 'Em uso'), ('maintenance', 'Manutenção'), ('inactive', 'Inativo')], default='available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['plate'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.vehicle', verbose_name='veículo'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('company', 'cpf'), name='unique_driver_cpf_company'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('company', 'plate'), name='unique_vehicle_plate_company'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['company', 'status'], name='operations__company_3c79ec_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['company', 'created_at'], name='operations__company_4e7a62_idx'),
        ),
    ]
