# Generated by Django 6.0.6 on 2026-08-11 23:59

import django.core.validators
import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_is_platform_alter_user_role_and_more'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aceita em'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude da entrega'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude da entrega'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acionada em'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='coletada em'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude da coleta'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude da coleta'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='última latitude'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_lng',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='última longitude'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_position_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='posição atualizada em'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Conta usada pelo entregador para entrar no painel dele.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário de acesso'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitada'), ('dispatching', 'Acionando entregador'), ('accepted', 'Aceita pelo entregador'), ('approved', 'Aprovada'), ('pickup', 'Em coleta'), ('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('canceled', 'Cancelada')], default='requested', max_length=12),
        ),
        migrations.AlterField(
            model_name='deliveryevent',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitada'), ('dispatching', 'Acionando entregador'), ('accepted', 'Aceita pelo entregador'), ('approved', 'Aprovada'), ('pickup', 'Em coleta'), ('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('canceled', 'Cancelada')], max_length=12),
        ),
        migrations.CreateModel(
            name='PickupChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_name', models.CharField(max_length=160, verbose_name='responsável que entregou o item')),
                ('handover_document', models.CharField(max_length=30, verbose_name='documento do responsável (RG/CPF)')),
                ('package_count', models.PositiveSmallIntegerField(default=1, verbose_name='volumes conferidos')),
                ('seal_number', models.CharField(blank=True, max_length=60, verbose_name='número do lacre')),
                ('identity_checked', models.BooleanField(verbose_name='confirmei a identidade do responsável pela entrega')),
                ('item_matches_request', models.BooleanField(verbose_name='o item confere com a solicitação da empresa')),
                ('packaging_intact', models.BooleanField(verbose_name='embalagem íntegra, sem sinal de violação')),
                ('seal_applied', models.BooleanField(verbose_name='lacre/selo aplicado e fotografado')),
                ('documents_checked', models.BooleanField(verbose_name='nota fiscal ou documento de acompanhamento conferido')),
                ('photos_are_original', models.BooleanField(verbose_name='declaro que as fotos foram tiradas agora, neste local')),
                ('temperature_ok', models.BooleanField(blank=True, default=False, verbose_name='acondicionamento térmico adequado')),
                ('notes', models.TextField(blank=True, verbose_name='observações da coleta')),
                ('lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude da coleta')),
                ('lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude da coleta')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='precisão (m)')),
                ('device', models.CharField(blank=True, max_length=255, verbose_name='dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciado em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='empresa')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_checklist', to='operations.delivery')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='operations.driver', verbose_name='motorista')),
            ],
            options={
                'verbose_name': 'checklist de coleta',
                'verbose_name_plural': 'checklists de coleta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='precisão (m)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='velocidade (m/s)')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='direção')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='operations.delivery')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='operations.driver', verbose_name='motorista')),
            ],
            options={
                'verbose_name': 'posição do motorista',
                'verbose_name_plural': 'posições dos motoristas',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['delivery', 'recorded_at'], name='operations__deliver_48bde6_idx'), models.Index(fields=['driver', 'recorded_at'], name='operations__driver__17048d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('01-local', '1 · Fachada ou recepção do local de coleta'), ('02-documento', '2 · Nota fiscal ou documento de acompanhamento'), ('03-item-geral', '3 · Item — visão geral'), ('04-item-etiqueta', '4 · Item — etiqueta ou identificação'), ('05-item-lado-a', '5 · Item — lado A'), ('06-item-lado-b', '6 · Item — lado B'), ('07-embalagem', '7 · Embalagem fechada'), ('08-lacre', '8 · Lacre ou selo de segurança'), ('09-carregado', '9 · Item acomodado no veículo'), ('10-placa', '10 · Placa do veículo'), ('11-odometro', '11 · Odômetro no início da corrida'), ('12-responsavel', '12 · Responsável pela entrega com o item')], max_length=20, verbose_name='etapa')),
                ('image', models.ImageField(upload_to=operations.models.checklist_photo_path, verbose_name='foto')),
                ('lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='operations.pickupchecklist')),
            ],
            options={
                'verbose_name': 'foto do checklist',
                'verbose_name_plural': 'fotos do checklist',
                'ordering': ['slot'],
                'constraints': [models.UniqueConstraint(fields=('checklist', 'slot'), name='unique_photo_per_slot')],
            },
        ),
    ]
