# Generated by Django 6.0.6 on 2026-08-12 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('operations', '0002_delivery_accepted_at_delivery_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor a repassar ao entregador'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='finance.invoice', verbose_name='fatura'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='finance.driverpayout', verbose_name='repasse'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculado pela tabela de preços e ajustável pelo admin master.', max_digits=10, verbose_name='valor cobrado da empresa'),
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=2, verbose_name='ordem')),
                ('address', models.CharField(max_length=255, verbose_name='endereço de entrega')),
                ('contact', models.CharField(blank=True, max_length=160, verbose_name='contato no destino')),
                ('lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações do destino')),
                ('receiver', models.CharField(blank=True, max_length=160, verbose_name='recebedor')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='operations.delivery')),
            ],
            options={
                'verbose_name': 'destino da entrega',
                'verbose_name_plural': 'destinos da entrega',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
