# Generated by Django 6.0.6 on 2026-08-12 21:53

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_delivery_driver_payout_amount_delivery_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='logradouro e número'),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_account',
            field=models.CharField(blank=True, max_length=25, verbose_name='conta'),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_agency',
            field=models.CharField(blank=True, max_length=15, verbose_name='agência'),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_name',
            field=models.CharField(blank=True, max_length=90, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_proof',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('entregadores'), validators=[core.uploads.validate_document_file], verbose_name='comprovante bancário'),
        ),
        migrations.AddField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, max_length=90, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_back',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('entregadores'), validators=[core.uploads.validate_document_file], verbose_name='CNH — verso'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_first_license_at',
            field=models.DateField(blank=True, null=True, verbose_name='data da primeira habilitação'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_front',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('entregadores'), validators=[core.uploads.validate_document_file], verbose_name='CNH — frente ou CNH digital'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_has_ear',
            field=models.BooleanField(default=False, help_text='Obrigatório para transportar carga de terceiros.', verbose_name='CNH com EAR (exerce atividade remunerada)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='data de emissão da CNH'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_register',
            field=models.CharField(blank=True, max_length=20, verbose_name='nº de registro da CNH'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF da CNH'),
        ),
        migrations.AddField(
            model_name='driver',
            name='criminal_record',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('entregadores'), validators=[core.uploads.validate_document_file], verbose_name='certidão de antecedentes criminais'),
        ),
        migrations.AddField(
            model_name='driver',
            name='district',
            field=models.CharField(blank=True, max_length=90, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=160, verbose_name='contato de emergência'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone de emergência'),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_certificate',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('entregadores'), validators=[core.uploads.validate_document_file], verbose_name='atestado ou exame médico (ASO)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='mother_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='nome da mãe'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pix_key',
            field=models.CharField(blank=True, max_length=140, verbose_name='chave Pix para repasse'),
        ),
        migrations.AddField(
            model_name='driver',
            name='portrait',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('entregadores'), validators=[core.uploads.validate_document_file], verbose_name='foto do entregador'),
        ),
        migrations.AddField(
            model_name='driver',
            name='proof_of_address',
            field=models.FileField(blank=True, help_text='Conta de água, luz ou telefone dos últimos três meses.', upload_to=core.uploads.document_path('entregadores'), validators=[core.uploads.validate_document_file], verbose_name='comprovante de residência'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rg_issuer',
            field=models.CharField(blank=True, max_length=20, verbose_name='órgão emissor do RG'),
        ),
        migrations.AddField(
            model_name='driver',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='driver',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('van', 'Furgão'), ('box', 'Baú'), ('open', 'Carroceria aberta'), ('refrigerated', 'Refrigerado')], max_length=14, verbose_name='tipo de carroceria'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='altura do compartimento (cm)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_length_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='comprimento do compartimento (cm)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_width_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='largura do compartimento (cm)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(blank=True, max_length=17, verbose_name='chassi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='crlv_document',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('veiculos'), validators=[core.uploads.validate_document_file], verbose_name='CRLV digital'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='crlv_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='vencimento do licenciamento'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='número de portas'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, choices=[('flex', 'Flex'), ('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('diesel', 'Diesel'), ('electric', 'Elétrico'), ('hybrid', 'Híbrido')], max_length=10, verbose_name='combustível'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='peso bruto total (kg)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_tracker',
            field=models.BooleanField(default=False, verbose_name='possui rastreador'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('veiculos'), validators=[core.uploads.validate_document_file], verbose_name='apólice do seguro'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='vencimento do seguro'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy',
            field=models.CharField(blank=True, max_length=60, verbose_name='número da apólice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurer',
            field=models.CharField(blank=True, max_length=90, verbose_name='seguradora'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lockable',
            field=models.BooleanField(default=False, verbose_name='compartimento com trava'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quilometragem atual'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano do modelo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_document',
            field=models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ do proprietário'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='proprietário no CRLV'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_cargo',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('veiculos'), validators=[core.uploads.validate_document_file], verbose_name='foto do compartimento de carga'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_front',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('veiculos'), validators=[core.uploads.validate_document_file], verbose_name='foto frontal'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_plate',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('veiculos'), validators=[core.uploads.validate_document_file], verbose_name='foto da placa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_rear',
            field=models.FileField(blank=True, upload_to=core.uploads.document_path('veiculos'), validators=[core.uploads.validate_document_file], verbose_name='foto traseira'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF da placa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='refrigerated',
            field=models.BooleanField(default=False, verbose_name='compartimento refrigerado'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='renavam',
            field=models.CharField(blank=True, max_length=11, verbose_name='RENAVAM'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='top_case_liters',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='capacidade do baú (litros)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tracker_provider',
            field=models.CharField(blank=True, max_length=90, verbose_name='empresa do rastreador'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cnh',
            field=models.CharField(max_length=20, verbose_name='número da CNH'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=160, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='ano de fabricação'),
        ),
    ]
