# Generated by Django 6.0.6 on 2026-08-12 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_address_proof_and_more'),
        ('finance', '0002_driverpayout_repasse_por_entregador_and_more'),
        ('operations', '0004_driver_address_driver_bank_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', '-created_at'], name='delivery_status_recentes'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'status'], name='delivery_por_entregador'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['delivery', '-created_at'], name='evento_por_entrega'),
        ),
    ]
